#!/bin/sh
case "$1" in
        *)
	chown -R www-data:www-data /usr/share/nextcloud
	chown -R www-data:www-data /var/lib/nextcloud
	chown -R www-data:www-data /etc/nextcloud/
	a2ensite nextcloud	
        ;;
esac


exit 0
